---
    - name: add nginx apt-key
      apt_key:
       url: http://nginx.org/keys/nginx_signing.key
       state: present

    - name: add nginx apt repository
      apt_repository:
       repo: 'deb http://nginx.org/packages/mainline/ubuntu/ xenial nginx'
       state: present
       filename: nginx
       update_cache: yes

    - name: install nginx
      apt:
       name: nginx
       state: present
       update_cache: yes

    - name: Install Tools
      apt: name={{item}} state=present update_cache=yes
      with_items:
       - python-httplib2

    - name: Configure nginx Site
      template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/demo mode=0644
      notify: restart nginx

    - name: deactivate default nginx site
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify: restart nginx

    - name: activate demo nginx site
      file: src=/etc/nginx/sites-available/demo dest=/etc/nginx/sites-enabled/demo state=link
      notify: restart nginx

    - name: ensure nginx started
      service: name=nginx state=started enabled=yes

