---
    - name: install apache
      apt: name={{item}} state=present update_cache=yes
      with_items:
       - apache2
       - libapache2-mod-wsgi

    - name: Ensure mod_wsgi enable
      apache2_module: state=present name=wsgi
      notify: restart apache2

    - name: De-active default apache site
      file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
      notify: restart apache2

    - name: enasure apache started
      service: name=apache2 state=started enabled=yes

